kirjavascript/TetrisGYM

- main.asm
When browsing through the code looking for where text-based sprites are set (e.g. `PAUSE`), the characters are not easily findable because they are set up directly as their mapped value.
Set the characters in the bytearrays in their readable form.
> Set sprite letters as character in byte arrays

- CHANGELOG.md
- README.md
- main.asm
In [qual mode](https://github.com/kirjavascript/TetrisGYM#qual-mode), wait screens are restored and not skipped, and curtain is restored too.
Re-adding the curtain was a restoration for timing sakes, but it also helped with post-processor tools like [NestrisChamps](https://github.com/timotheeg/nestrischamps) which, when curtain is not present, can not detect the game-over event reliably.
In this PR, the Classic Tetris pause screen is also restored. With the way TetrisGYM was overlaying the characters `PAUSE` on the field, post-processing tools would incorrectly detect the characters as blocks in the field.
1. Restore black-screen pause from Classic Tetris (including repositioning the pause text to match)
2. Update readme file to add these details
With a black screen, the block mode is not …
> Restore standard pause in qual mode

- build.sh
- src/constants.asm
- src/io.asm
- src/main.asm
- src/nmi/nmi.asm
- src/nmi/pollkeyboard.asm
- src/ram.asm
Added code to read Family BASIC Keyboard and map to button input.  
The 72 keys are mapped to 9 consecutive bytes at $0677
Arrow keys are mapped to D-PAD buttons.  
Return is mapped to Start. 
Right shift is mapped to Select.  
Grph is mapped to B.  
Space is mapped to A.  
The mapped keys are stored in newlyPressedKeys and heldKeys and are then copied to newlyPressedButtons_player1 and heldButtons_player1 respectively.  
All keyboard code is compiled based on KEYBOARD flag.  Modified build.sh script to use args, with the arg -m option used to set mapper.  -k sets KEYBOARD flag, and -v sets the -x flag so full command output is shown.  
resolves #31
> Famicom keyboard

- build.sh
This is testing for the presence of clean.nes before attempting to create the patch.  It also tests for sha1sum then shasum before running either.  Lastly it tests for the existence of the patch before attempting a stat, and depending on mac, will run the appropriate command to return the size.   
This should make build.sh more compatible and may eliminate the need for build-compat.sh.
> add mac support

- src/gamemode/waitscreen.asm
Use bank0 during legal screen.  Unnoticeable unless additional tiles are being used from the rocket screen nametable.
> switch to bank 0 for legal screen

- src/gamemodestate/pause.asm
- src/modes/debug.asm
Another for your consideration.  I noticed that debug mode was easy to instantly end a game if you unpaused in the wrong position, so I dug into the code and made tweaks.  
Here's the changes:
Prevent unpausing if position is invalid.
Prevent switching from tile placer (not sure what to call it) if position is invalid.
TetriminoX and TetriminoY are now constrained to the playfield when using tile placer, looping from side to side or between top & bottom.  
Piece selection cycles from longbar to T or T to longbar instead of stopping.
> Safer debug mode

- src/io.asm
- src/main.asm
Fixes #46 
This replaces the code at $8000 which was used for the MMC1 reset.  Previously it was ldy ($a0) and has been replaced with ldx ($a2).  Both of these values have a 1 in bit 7 which is the only bit that's significant for the reset.  https://www.nesdev.org/wiki/MMC1#Reset
> Move region code

- src/io.asm
This eliminates the need for the code at $8000 to start with a particular opcode.
> independent mmc1 reset

- src/gamemodestate/pause.asm
- src/util/core.asm
Reduces the clearing of OAM from 2872 cycles to 1047 by resetting only the y variable for each of the 64 sprite slots.  
This is related to a separate effort of sending data to nestrischamps via an everdrive.  The process to ship the data out currently takes 2100 cycles.  While currently I don't think that process is running past NMI, this looked like an easy opportunity to get some breathing room.
> Faster oam reset

- src/audio.asm
- src/boot.asm
- src/gamemode/gametypemenu/menu.asm
- src/gamemode/waitscreen.asm
- src/gamemodestate/handlegameover.asm
- src/gamemodestate/initstate.asm
- src/modes/debug.asm
- src/modes/garbage.asm
- src/modes/qtap.asm
- src/modes/tapqty.asm
- src/modes/tspins.asm
- src/nmi/render_mode_play_and_demo.asm
- src/nmi/render_score.asm
- src/nmi/render_util.asm
- src/playstate/active.asm
- src/playstate/completedrows.asm
- src/playstate/gameover_rocket.asm
- src/playstate/spawnnext.asm
- src/playstate/updatestats.asm
These are a few minor optimizations that save a total of 70 bytes.
Comparisons to zero identified with `grep -RP 'cm?p[yx]?\s+#\$?0?0\b' ./src`
There were a few instances where the comparison was necessary as the zero flag would be unknown at the time of the comparison and were left alone.    The remaining instances were either commented out altogether or altered to produce the same result with fewer bytes.
There were also a few instances of values being loaded into the accumulator that were already there, identified with `grep -zoRP '(?mi)lda\s+(\w+)\s+cmp\s+\S+\s*$\s+b..\s+\S+\s*$\s+lda \1\s*$\s' src/`
Reference:
http://forum.6502.org/viewtopic.php?f=12&t=4434#p50991
http://www.6502.org/tutorials/6502opcodes.html
> Use zero flag and values left in accumulator

- src/nmi/render_score.asm
Fixes the classic score renderer erroneously adding 1 to the 100k's digit due to not clearing a carry flag.
This bug is triggered when the millions digit in the score has bit 3 set, and is the bug in P1xelAndy's [WR run](https://www.youtube.com/live/7Iz3Ogo3fUI?si=-2b7nPpPrvalTNKN&t=8188).
> Fix classic score renderer bug

- src/gamemodestate/initstate.asm
- src/modes/floor.asm
- src/playstate/completedrows.asm
- src/playstate/updatestats.asm
- src/ram.asm
This fixes a bug introduced in #50
Replaced floorModifier with currentFloor.  This allows for linecap floor to modify the floor variable without modifying what's displayed for floor mode on the menu.  
Validated that floor mode 0 does not clear lines.  All other floor modes behave as expected.  Linecap floor works as expected, growing the floor each level up.  Linecap floor works with floor mode but with the only caveat being that normal floor mode uses BLOCK_TILES, while linecap floor uses BLOCK_TILES+3.
> Fix linecap floor top row bug

- src/modes/tspins.asm
Fixes issue introduced in #57 
The `cmp #0` was setting the carry bit, causing an extra bit to be added.  Changed to explicitly add 2 to restore expected behavior.
> fix: tspin render

- src/util/core.asm
Linecap menu was black text on black background making it difficult to read.
> fix: don't black out palette when clearing nametable

- src/nmi/render_mode_play_and_demo.asm
- src/nmi/render_util.asm
Removes the need for adding 6 when referencing the vramPlayfieldRows table
> Save cycles/bytes by removing offset for 2 player support

- src/playstate/preparenext.asm
This change was part of the lowstack mode change.  Broke it out so it can be tested/incorporated separately to facilitate the crash graphic for Hydrant's crash mode.  
Supports an entrypoint that allows for setting a custom row to display the graphic, used in lowstack so the graphic never overlaps with the line.
> feature: playfield graphic function

- src/playstate/active.asm
- src/sprites/piece.asm
vramRow was being reset unnecessarily after a sonic drop.  This meant if hard drop occurred in the next 4 frames, lockTetrimino would exit prematurely and nothing would end up stored in the playfield.  
Also forced display of next piece when block tool is enabled and when in hard drop mode
> Harddrop tweaks

- tests/src/garbage.rs
- tests/src/main.rs
Detect if NMI occurs outside of the expected wait loop.  Tested this against the commit just before the RNG optimization (5a390c3) and the test fails.  Tests on current master succeed.
> validate garbage 4 nmi occurs during wait loop

- CHANGELOG.md
- src/gamemodestate/initstate.asm
- src/modes/hz.asm
- src/nmi/render_hz.asm
- src/nmi/render_mode_play_and_demo.asm
- src/playstate/gameover_rocket.asm
- src/playstate/garbage.asm
- src/playstate/spawnnext.asm
- tests/src/cycle_count.rs
- tests/src/hz_display.rs
- tests/src/input.rs
- tests/src/main.rs
- tests/src/nmi.rs
- tests/src/util.rs
- tests/src/video.rs
See title. In addition, I wrote a couple of light tests and kept the hz display enabled during topout (quality of life thing I've wanted for a while). More detailed notes on the process can be found [here](https://github.com/kirjavascript/TetrisGYM/commit/2fc570e8f92f9258a05907edf3b6743433f21a24) and [here](https://github.com/kirjavascript/TetrisGYM/commit/938d0666d6b61c9202de3465e944e09a0f5458f0).
testing is very cool i kind of want to add stuff for crash gym but that seems like a lot so maybe later
> Add negative delay to the hz display

- src/modes/crash.asm
A bugfix for lag frames happening when they aren't supposed to, and strict mode now applies to confetti, desyncs, etc.
> Finishing touches to crash detection

- src/modes/floor.asm
- src/playstate/completedrows.asm
- src/playstate/updatestats.asm
- tests/src/floor.rs
Re: #104 
Line based floor caps outside of levelups were broken.  This uses a temp variable to track when the linecounter crosses a multiple of 10 so the appropriate logic can be applied.
This also modifies the floor tile used so linecap floor & regular floor modes match.
> linecap floor logic occurs when levelups possible

- tests/src/sps.rs
Noticed that `000206` gave the wrong first piece when compared to the actual game, tracked it down to spawnID not being zero at the beginning of the sequence.
> Reset spawnID between SPS sequence tests

- tests/src/tspins.rs
There's no issue with the current test in place, but I remember it taking a little bit of effort to figure out how to read a tile from the nametable.  This serves as a reminder for how to do the same if it's ever needed again.
> Read tile from nametable in tspins test

- CHANGELOG.md
- src/gamemode/levelmenu.asm
Opens up most of the score reset code to be default and not behind the build flag. 
Code to clear saved high scores is still behind build flag and detects SRAM before resetting.
> Reset scores when no SRAM is present

- tests/src/tspins.rs
The tiles used by the tspin function changed from 0x7b to 0x7e in cb895c47101236223e6ad0308a63f4b90b30962c and broke this test.  This fixes that.
> update tspins test to look for 0x7e instead of 0x7b

- src/audio.asm
Topout sound disappeared due to 3e541b0b8b52e3fbce7723be17b33099e2fd6e06.  Fixed by padding by one byte.   The low byte of the sound effect is loaded into the y register, a shared routine uses that being equal to zero as a condition to skip over the init routine.   
https://github.com/kirjavascript/TetrisGYM/blob/d81543a6c645aa22a7acbe219dcebadd88bdedca/src/audio.asm#L405-L409
https://github.com/kirjavascript/TetrisGYM/blob/d81543a6c645aa22a7acbe219dcebadd88bdedca/src/audio.asm#L338-L344
> Fix topout sound

- src/modes/floor.asm
This subtract is currently relying on the carry being set by the cmp that occurs before branching
> set carry before subtract in floor

- src/modes/crunch.asm
- src/playstate/completedrows.asm
- src/playstate/util.asm
- src/ram.asm
This should fix #103 and supersede #117
This uses 2 bytes of ram to store unpacked data derived from `crunchModifier` to speed up the column drawing function.  This also simplifies the modification of `checkMusicSpeed` so that the crunch columns don't interfere with allegro.  The additional bytes used in `checkMusicSpeed` were saved in the rewriting of crunch so there's no additional romspace used.
> optimized crunch with crash mode accommodated

- src/gamemodestate/initstate.asm
Noticed that after switching the crash mode to `SHOW` from `TOPOUT` after a crash, the next game would show a crash.    This doesn't happen when resetting crashState to 0 at game init.
> Clear crashState at game init

- tests/src/harddrop.rs
- tests/src/main.rs
Put together to measure cycle count in the routines used by harddrop, mainly isPositionValid.  Not an exhaustive test but is a starting point for further testing.  Maximum cycles measured in playerControlsActiveTetrimino at the time of this commit is 21,875.
> add harddrop.rs

- src/data/orientation.asm
- src/playstate/spawnnext.asm
- src/sprites/loadsprite.asm
- src/sprites/piece.asm
orientationToSpriteTable is used to map the spawnId to the arbitrary sprite ID for the next piece.  Reordering the sprites to match the game's piece ID order and reusing tetriminoTypeFromOrientation, this table can be removed.
spawnOrientationFromOrientation may have been created in development when the RNG produced the orientation ID instead of the piece ID, but random spawn orientations weren't desired.  As it's currently being used to convert the spawn ID to the same spawn ID, it can be removed.
Reduces PRG usage by 38 bytes
> remove unneeded legacy tables

- src/boot.asm
> Clean unused init bytes

- CHANGELOG.md
- README.md
- src/constants.asm
- src/gamemode/levelmenu.asm
- src/playstate/updatestats.asm
Closes #137.  Adds marathon modes 3 & 4 that are like 1 & 2 except with scoring that matches the displayed level.
> Add marathon modes 3 & 4

- src/gamemode/gametypemenu/menu.asm
- src/main.asm
- src/nmi/render_mode_pause.asm
- src/nmi/render_mode_play_and_demo.asm
https://github.com/kirjavascript/TetrisGYM/blob/2ba3d20f73ffd27de254f09733297dfbfac6e359/src/util/strings.asm#L72
When messing around with these strings I realized the feature force_range could cause problems here (and probably other places) that wouldn't be immediately apparent.  It was only added for a cleaner looking syntax.  Removing.
> remove 'feature force_range'
